package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        add {
            notifications {
                notifierSettings = emailNotifier {
                    email = "marcin.laskowski.07@gmail.com"
                }
                buildFinishedSuccessfully = true
            }
        }
    }
}
